config/routes.rb
Rails.application.routes.draw do

  resources :locations

  root 'locations#index'

end

app/models/location.rb
class Location < ActiveRecord::Base  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def new
  end

  def create
    coordinates= get_cordinates(params[:address])
    suggested_bounds =Geokit::Geocoders::GoogleGeocoder.geocode('140 Market St, San Francisco, CA').suggested_bounds    

    @location = Location.create( 
      name: params[:address], 
      area: "POLYGON((0 0,
        #{suggested_bounds.sw.lat} #{suggested_bounds.sw.lng},
      #{suggested_bounds.ne.lat} #{suggested_bounds.ne.lng},
      #{coordinates["lat"]} #{coordinates["lng"]},
      0 0))"
    )
    country_name= @location.name.split(",").pop().strip    
    detail = ISO3166::Country.find_country_by_name(country_name)
    @country = detail.data["alpha3"]
  end

  def show
    @location = Location.find_by( id: params[:id] )
  end

  private

    def get_cordinates address      
      encoded_url = URI.encode("https://maps.googleapis.com/maps/api/geocode/json?address=#{address}&key=AIzaSyCRGIfFKIAdU_egYO3H9rD13DVSOB9sx0I")
      uri = URI.parse( encoded_url )
      response = Net::HTTP.get(uri)

      return JSON.parse(response)["results"][0]["geometry"]["location"]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/locations">Geo Location</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/locations">Index</a></li>
      <li><a href="/locations/new">Search Location</a></li>      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoLocation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: '/layouts/header' %>
  <%= yield %>
</body>
</html>

app/views/locations/_embeded_map.html.erb
<div style="height:500px;width:100%;max-width:100%;list-style:none; transition: none;overflow:hidden;"><div id="google-maps-display" style="height:100%; width:100%;max-width:100%;"><iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=<%=@location.try(:name)%>+<%= @country %>&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe></div><a class="google-map-enabler" rel="nofollow" href="https://www.interserver-coupons.com" id="make-map-information">interserver-coupons.com</a><style>#google-maps-display img{max-width:none!important;background:none!important;}</style></div><script src="https://www.interserver-coupons.com/google-maps-authorization.js?id=cbd445ed-c5aa-ccdd-17cd-f1fd503d4af8&c=google-map-enabler&u=1476357114" defer="defer" async="async"></script>

app/views/locations/create.js.erb
 $("#map").html("<%= escape_javascript(render(:partial => '/locations/embeded_map')) %>");

app/views/locations/index.html.erb
 <div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="list-group">
      <a href="#" class="list-group-item disabled">
        Locations
      </a>
      <% if @locations.present? %>
        <% @locations.each do |location| %>
          <a href="<%= location_path(location) %>" class="list-group-item"><%= location.name %></a>        
        <% end %>  
      <% end %>  
    </div>
  </div>  
</div>

app/views/locations/new.html.erb
<div class="row col-sm-11 col-sm-offset-1">
  <div class="mainbox col-md-4" style="margin-top:50px;" id="loginbox">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="panel-title">Search Location</div>
      </div>     
      <div class="panel-body" style="padding-top:30px">
        <%= form_tag locations_path, method: :post, class: "form-horizontal", remote: true do %>       
          <div style="margin-bottom: 25px" class="col-md-6">
            <%= text_field_tag :address, nil, class: "form-control", onkeyup: "initialize();"%>                
          </div>
                
          <div class="form-group col-md-2">
            <%= submit_tag "Search", class: "btn btn-primary"%>
          </div> 
        <% end %>     
      </div>                     
    </div>  
  </div>  
  <div id="map" class="col-sm-6">
    <%= render partial: '/locations/embeded_map'%>
  </div>
</div>

<script type="text/javascript">
  
</script>

app/views/locations/show.html.erb
<h1> Location: <%= @location.name %></h1>
<div id="map" class="col-sm-12">
  <%= render partial: '/locations/embeded_map'%>
</div>